import { describe, expect, test } from 'bun:test'

describe('shared agent chat prompt design', () => {
  test('uses one quiet shared composer in Board objects and the sidebar', async () => {
    const prompt = await Bun.file('src/components/ai-elements/AiPromptInput.vue').text()
    const surface = await Bun.file('src/components/ai-elements/AiConversationSurface.vue').text()
    const boardChat = await Bun.file(
      'src/components/agent-terminal/AgentConversationBoardSurface.vue'
    ).text()
    const sidebarChat = await Bun.file('src/components/agent-chat/AgentChatsPanel.vue').text()

    expect(prompt).toContain('min-h-[48px]')
    expect(prompt).toContain('rounded-[14px]')
    expect(prompt).toContain("narrow ? 'size-9' : 'size-10'")
    expect(prompt).toContain('useElementSize(form)')
    expect(prompt).toContain(':icon-only="narrow"')
    expect(prompt).toContain(':mini="veryNarrow"')
    expect(prompt).toContain("veryNarrow.value ? 'Message…' : placeholder")
    expect(prompt).toContain("'mx-1.5 mb-2 min-h-[40px] rounded-[11px]'")
    expect(prompt).toContain('border-chrome-control-border')
    expect(prompt).toContain('focus-within:border-surface/15')
    expect(prompt).not.toContain('focus-within:ring-2')
    expect(prompt).toContain('disabled:placeholder:text-muted')
    expect(prompt).toContain('disabled:text-muted/45')
    expect(prompt).not.toContain('rounded-[27px]')
    expect(prompt).not.toContain('ring-chrome-control-border')
    expect(prompt).toContain('stroke-[1.8]')
    expect(prompt).not.toContain('disabled:bg-surface/75')
    expect(prompt).not.toContain('disabled:text-panel/65')
    expect(prompt).not.toContain('disabled:opacity-30')
    expect(prompt).not.toContain('disabled:opacity-50')
    expect(prompt).toContain('rows="1"')
    expect(prompt).toContain('!modelValue.trim() || dictating')
    expect(surface).toContain('<AiPromptInput')
    expect(surface).toContain(':interactive="promptInteractive"')
    expect(surface).toContain('promptInteractive = true')
    expect(prompt).toContain("isInteractive ? 'pointer-events-auto' : 'pointer-events-none'")
    expect(prompt).toContain('interactive !== false')
    expect(prompt).toContain('@pointerdown="activateComposer"')
    expect(boardChat).toContain('<AiConversationSurface')
    expect(boardChat).toContain(':prompt-interactive="interactionEnabled"')
    expect(boardChat).toContain('@activate="emit(\'activate\')"')
    expect(sidebarChat).toContain('<AiConversationSurface')
  })

  test('groups chronological activity once and collapses it when a run completes', async () => {
    const surface = await Bun.file('src/components/ai-elements/AiConversationSurface.vue').text()
    const activity = await Bun.file('src/components/ai-elements/AiActivityDisclosure.vue').text()
    const message = await Bun.file('src/components/ai-elements/AiMessage.vue').text()
    const commentary = await Bun.file('src/components/ai-elements/AiCommentary.vue').text()
    const tool = await Bun.file('src/components/ai-elements/AiToolCall.vue').text()
    const boardChat = await Bun.file(
      'src/components/agent-terminal/AgentConversationBoardSurface.vue'
    ).text()

    expect(boardChat).toContain('conversationMessages')
    expect(boardChat).not.toContain(' compact')
    expect(surface).not.toContain('v-if="compact"')
    const runs = await Bun.file('src/components/ai-elements/conversation-runs.ts').text()
    expect(surface).toContain('<AiActivityDisclosure')
    const firstDisclosure = surface.slice(
      surface.indexOf('<AiActivityDisclosure'),
      surface.indexOf('<AiMessageItem', surface.indexOf('<AiActivityDisclosure'))
    )
    expect(firstDisclosure).not.toContain('v-if=')
    expect(surface).toContain('v-for="{ run, runIndex } in paintedRuns"')
    expect(surface).toContain('conversationRuns(messages')
    expect(surface).toContain('conversationRunWindow(')
    expect(runs).toContain(
      'endedAt: run.prompt?.completedAt ?? latestMessageCreatedAt(run.messages)'
    )
    expect(surface).toContain(':ended-at="run.endedAt"')
    expect(activity).toContain('const expanded = ref(staysOpen.value)')
    expect(activity).toContain('expanded.value = value')
    expect(activity).toContain('groupActivityTimeline')
    expect(activity).toContain(':open="item.open"')
    expect(activity).toContain(':aria-expanded="expanded"')
    expect(activity).toContain(":aria-label=\"expanded ? 'Hide thought' : 'Show thought'\"")
    expect(activity).toContain('v-for="item in commentaries"')
    expect(activity).toContain('v-for="item in reasonings"')
    expect(activity).toContain('v-for="item in toolGroups"')
    expect(activity).toContain('<AiReasoning')
    expect(activity).toContain('`Thought for ${duration.value}`')
    expect(activity).toContain('agent-thought-shimmer')
    expect(activity).toContain("return 'Thinking'")
    expect(activity).not.toContain('ai-thought-well')
    expect(activity).not.toContain("expanded && hasWork ? 'opacity-0' : 'opacity-100'")
    expect(activity).toContain('data-test-id="ai-turn-duration"')
    expect(activity.indexOf('v-for="item in commentaries"')).toBeLessThan(
      activity.indexOf('data-test-id="ai-turn-duration"')
    )
    expect(activity.indexOf('data-test-id="ai-turn-duration"')).toBeLessThan(
      activity.indexOf('v-for="item in reasonings"')
    )
    expect(activity.indexOf('v-for="item in reasonings"')).toBeLessThan(
      activity.indexOf('v-for="item in toolGroups"')
    )
    expect(surface.indexOf('<AiActivityDisclosure')).toBeLessThan(
      surface.indexOf('v-for="message in run.visible"')
    )
    expect(activity).toContain('resolveCommentaryActivityState')
    expect(activity).toContain('resolveToolActivityState')
    expect(activity).toContain('elapsedMs.value < 1_000')
    expect(activity).not.toContain('ai-tool-group')
    expect(message).not.toContain('hideActivity = true')
    expect(message).not.toContain('<AiReasoning')
    expect(message).not.toContain('<AiToolCall')
    expect(message).not.toContain(':compact="compact"')
    expect(commentary).toContain('data-test-id="ai-commentary"')
    expect(commentary).not.toContain('<button')
    expect(commentary).not.toContain('<icon-')
    expect(tool).not.toContain('normalizedName')
    expect(tool).not.toContain('icon-lucide-square-terminal')
    expect(tool).toContain('toolCallProgressLabel')
    expect(tool).toContain("AiToolState | 'stopped'")
    expect(tool).toContain('data-test-id="ai-tool-input"')
    expect(tool).toContain('data-test-id="ai-tool-label"')
    expect(tool).toContain('max-h-40')
  })

  test('keeps the Chats sidebar to one list or one conversation at a time', async () => {
    const sidebarChat = await Bun.file('src/components/agent-chat/AgentChatsPanel.vue').text()

    expect(sidebarChat).toContain('const view = agentChatsPanelView')
    expect(sidebarChat).toContain('v-show="view === \'list\'"')
    expect(sidebarChat).toContain('v-show="view === \'conversation\'"')
    expect(sidebarChat).toContain('data-test-id="agent-thread-back"')
    expect(sidebarChat).toContain('data-test-id="agent-selected-new"')
    expect(sidebarChat).toContain('icon-lucide-loader-circle')
    expect(sidebarChat).not.toContain('function stateTone')
    expect(sidebarChat).not.toContain('function showStateDot')
    expect(sidebarChat).toContain(':aria-current="selectedId === thread.id ? \'true\' : undefined"')
    expect(sidebarChat).not.toContain('DISPATCHERS')
    expect(sidebarChat).not.toContain('TASK HISTORY')
    expect(sidebarChat).not.toContain('agent-pool-summary')
    expect(sidebarChat).not.toContain('{{ thread.routingKey }}')
    expect(sidebarChat).not.toContain('agent-conversation-state')
    expect(sidebarChat).not.toContain('function headerStatus')
    expect(sidebarChat).not.toContain('panelTitle(selectedThread)')
    expect(sidebarChat).not.toContain(
      ':empty-description="threadLiveWorkingLabel(selectedThread, now.getTime())"'
    )
    expect(sidebarChat).not.toContain("kind === 'dispatcher'")
    expect(sidebarChat).toContain('{{ agentConversationDisplayTitle(thread) }}')

    const boardChat = await Bun.file(
      'src/components/agent-terminal/AgentConversationBoardSurface.vue'
    ).text()
    expect(boardChat).toContain('data-test-id="agent-conversation-working"')
    expect(boardChat).toContain('icon-lucide-loader-circle')
    expect(boardChat).not.toContain('agent-conversation-status-dot')
    expect(boardChat).not.toContain('agent-conversation-status-label')
    expect(boardChat).not.toContain(':empty-description="workingLabel || thread?.recentUpdate"')
    expect(boardChat).not.toContain('backdrop-blur-xl')
    expect(boardChat).not.toContain("kind === 'dispatcher'")

    const overlays = await Bun.file(
      'src/components/agent-terminal/AgentTerminalOverlays.vue'
    ).text()
    expect(overlays).not.toContain('AgentRoutingConnections')
    expect(overlays).not.toContain('createAgentTerminalDocument')
    expect(overlays).not.toContain('createDispatcherObject')
  })

  test('lets a click in the Board composer reach the input and enter the chat', async () => {
    const overlays = await Bun.file('src/components/canvas/CodeObjectOverlays.vue').text()
    const conversation = await Bun.file('src/components/ai-elements/AiConversation.vue').text()
    const prompt = await Bun.file('src/components/ai-elements/AiPromptInput.vue').text()
    const styles = await Bun.file('src/app.css').text()
    const boardChat = await Bun.file(
      'src/components/agent-terminal/AgentConversationBoardSurface.vue'
    ).text()

    expect(overlays).toContain('agentDocumentFor(frame)')
    expect(overlays).toContain('liveIframeHostStyle(style)')
    expect(overlays).toContain('isSmylrProductionFrame(frame) || isSmylrComponentCodeObject(frame)')
    expect(overlays).not.toContain("contentVisibility: 'auto'")
    expect(overlays).toContain('@activate="enterSurfaceInteraction(frame, true)"')
    expect(overlays).toContain("agentDocumentFor(frame) ? 'bottom-[4.75rem]' : 'bottom-0'")
    expect(overlays).toContain("mode === 'interact' && frame && !agentDocumentFor(frame)")
    expect(conversation).toContain('tabindex="-1"')
    expect(conversation).not.toContain('tabindex="0"')
    expect(conversation).toContain('useStickToBottom')
    expect(boardChat).toContain('shouldRouteKeyToAgentComposer')
    expect(boardChat).toContain('@focusin="keepComposerFocused"')
    expect(prompt).toContain('activateComposer')
    expect(prompt).toContain('select-text')
    expect(prompt).toContain('} = defineProps<')
    expect(prompt).not.toContain('useTextareaAutosize')
    expect(prompt).not.toContain('} = props')
    expect(boardChat).toContain('select-text')
    expect(boardChat).toContain('{ capture: true }')
    expect(styles).toContain('user-select: text')
    expect(styles).toContain('-webkit-user-select: text')
  })

  test('does not remount or snap the transcript on each working update', async () => {
    const conversation = await Bun.file('src/components/ai-elements/AiConversation.vue').text()
    const surface = await Bun.file('src/components/ai-elements/AiConversationSurface.vue').text()
    const activity = await Bun.file('src/components/ai-elements/AiActivityDisclosure.vue').text()
    const modelSelect = await Bun.file(
      'src/components/ai-elements/AiModelAndEffortSelect.vue'
    ).text()
    const promptInput = await Bun.file('src/components/ai-elements/AiPromptInput.vue').text()
    const sidebarChat = await Bun.file('src/components/agent-chat/AgentChatsPanel.vue').text()
    const boardChat = await Bun.file(
      'src/components/agent-terminal/AgentConversationBoardSurface.vue'
    ).text()

    expect(conversation).toContain('ref="scrollRef"')
    expect(conversation).toContain('ref="contentRef"')
    expect(conversation).toContain('useStickToBottom')
    expect(conversation).not.toContain('pinToBottomIfLocked')
    expect(conversation).not.toContain('bindContentRef')
    expect(conversation).not.toContain('onUpdated')
    expect(surface).toContain('function hasAnnotationLayout')
    expect(surface).toContain('if (hasAnnotationLayout()) refreshAnnotationGeometry()')
    expect(surface).toContain('if (!hasAnnotationLayout()) return')
    expect(activity).toContain(':css="!busy"')
    expect(surface).toContain('conversationWindowFollowsLatest')
    const markdown = await Bun.file('src/components/ai-elements/AiMarkdown.vue').text()
    expect(markdown).toContain('useStreamedText')
    expect(surface).toContain('nextConversationRunHeight')
    expect(surface).toContain('allowShrink: !(busy.value && latest?.id === runId)')
    const toolGroup = await Bun.file('src/components/ai-elements/AiToolGroup.vue').text()
    expect(toolGroup).toContain(':css="!busy"')
    expect(toolGroup).not.toContain('appear')
    expect(sidebarChat).not.toContain('threadLiveWorkingLabel(selectedThread, now.getTime())')
    expect(boardChat).toContain(':working-label="thread?.recentUpdate || \'\'"')
    expect(boardChat).not.toContain(':working-label="workingLabel"')
    expect(sidebarChat).toContain('agentChatsPanelSelectedId')
    expect(sidebarChat).toContain('agentChatsPanelView')
    expect(sidebarChat).toContain("view.value === 'conversation' && selectedId.value")
    expect(sidebarChat).toContain("selectedId || 'conversation'")
    expect(sidebarChat).toContain('input?.focus({ preventScroll: true })')
    expect(sidebarChat).toContain('overflow-clip')
    expect(surface).toContain('overflow-clip')
    expect(conversation).toContain('overflow-clip')
    expect(modelSelect).toContain('@close-auto-focus.prevent')
    expect(promptInput).toContain('@close-auto-focus.prevent')
  })
})
