import { describe, expect, test } from 'bun:test'

describe('shared agent chat prompt design', () => {
  test('uses one quiet shared composer in Board objects and the sidebar', async () => {
    const prompt = await Bun.file('src/components/ai-elements/AiPromptInput.vue').text()
    const surface = await Bun.file('src/components/ai-elements/AiConversationSurface.vue').text()
    const boardChat = await Bun.file(
      'src/components/agent-terminal/AgentConversationBoardSurface.vue'
    ).text()
    const sidebarChat = await Bun.file('src/components/agent-chat/AgentChatsPanel.vue').text()

    expect(prompt).toContain('compact = false')
    expect(prompt).toContain(
      "? 'agent-bot-composer mb-3 min-h-11 rounded-[22px] shadow-agent-composer'"
    )
    expect(prompt).toContain(": 'w-full rounded-[10px] shadow-none'")
    expect(prompt).toContain(
      ": 'agent-conversation-column mb-3 rounded-[12px] shadow-agent-composer'"
    )
    expect(prompt).toContain("? 'min-h-8 py-1.5 text-[11.5px] leading-[18px]'")
    expect(prompt).toContain(": 'min-h-10 py-2 text-[13px] leading-5'")
    expect(prompt).toContain('border-chrome-control-border')
    expect(prompt).toContain('focus-within:border-surface/15')
    expect(prompt).not.toContain('focus-within:ring-2')
    expect(prompt).toContain('disabled:placeholder:text-muted')
    expect(prompt).toContain('disabled:text-muted/45')
    expect(prompt).not.toContain('useElementSize(form)')
    expect(prompt).not.toContain('ring-chrome-control-border')
    expect(prompt).toContain('stroke-[1.8]')
    expect(prompt).not.toContain('disabled:bg-surface/75')
    expect(prompt).not.toContain('disabled:text-panel/65')
    expect(prompt).not.toContain('disabled:opacity-30')
    expect(prompt).not.toContain('disabled:opacity-50')
    expect(prompt).toContain('rows="1"')
    expect(prompt).toContain('const canSend = computed(')
    expect(surface).toContain('<AiPromptInput')
    expect(prompt).toContain('@pointerdown="focusComposer"')
    expect(boardChat).toContain('<AiConversationSurface')
    expect(boardChat).toContain(":class=\"interactionEnabled ? '' : 'pointer-events-none'\"")
    expect(boardChat).toContain(':inert="!interactionEnabled"')
    expect(sidebarChat).toContain('<AiConversationSurface')
  })

  test('keeps the annotated composer and selected header chrome quiet', async () => {
    const prompt = await Bun.file('src/components/ai-elements/AiPromptInput.vue').text()
    const sidebarChat = await Bun.file('src/components/agent-chat/AgentChatsPanel.vue').text()
    const surface = await Bun.file('src/components/ai-elements/AiConversationSurface.vue').text()

    expect(prompt).toContain('<icon-lucide-plus class="size-4 stroke-[1.8]" />')
    expect(prompt).not.toContain('<IconlyIcon name="plus" class="size-4" />')
    expect(sidebarChat).toContain('class="mt-2 flex h-10 shrink-0 items-center gap-1.5 px-2"')
    expect(sidebarChat).toContain("headerMode: 'inherit'")
    expect(surface).toContain("headerMode?: 'inherit' | 'surface'")
    expect(surface).toContain("headerMode === 'inherit' ? 'bg-sidebar-header' : 'bg-agent-surface'")
    expect(surface).toContain("? 'from-sidebar-header via-sidebar-header/80'")
    expect(surface).toContain(": 'from-agent-surface via-agent-surface/80'")
  })

  test('uses a neutral waveform treatment for active dictation', async () => {
    const prompt = await Bun.file('src/components/ai-elements/AiPromptInput.vue').text()
    const dictation = await Bun.file('src/app/speech-dictation.ts').text()
    const waveform = await Bun.file('src/components/ai-elements/AiVoiceWaveform.vue').text()

    expect(prompt).toContain('<AiVoiceWaveform')
    expect(prompt).toContain('rounded-full border border-transparent')
    expect(prompt).toContain(": 'border-surface/40 text-surface'")
    expect(prompt).toContain("showDictation && !compactConversation ? 'ml-1.5' : ''")
    expect(prompt).toContain(
      "compactConversation ? 'pointer-events-auto bg-agent-bot-user-bubble text-white'"
    )
    expect(prompt).not.toContain('aria-pressed:bg-accent')
    expect(prompt).not.toContain('<icon-lucide-mic-off v-if="dictating"')
    expect(prompt).not.toContain('ai-dictation-wave-speaking')
    expect(waveform).toContain("getContext('2d')")
    expect(waveform).toContain("reducedMotion.value !== 'reduce'")
    expect(waveform).toContain('levels[index]')
    expect(waveform).toContain("context.lineCap = 'round'")
    expect(dictation).toContain('export const speechDictationSpeaking = ref(false)')
    expect(dictation).toContain('export const speechDictationWaveform = ref<number[]>')
    expect(dictation).toContain('navigator.mediaDevices.getUserMedia')
    expect(dictation).toContain('analyser.getByteFrequencyData(frequencies)')
    expect(dictation).toContain("browserRecognition.addEventListener('speechstart'")
    expect(dictation).toContain("browserRecognition.addEventListener('speechend'")
    expect(prompt).toContain('const showDictation = computed(')
    expect(prompt).toContain('const showSend = computed(')
    expect(prompt).toContain('(dictating.value || (!showStop.value && !showRetry.value))')
    expect(prompt).toContain('dictating.value ||')
    expect(prompt).toContain('v-if="showDictation && (!compactConversation || !showSend)"')
    expect(prompt).toContain('v-if="showSend"')
    expect(prompt).toContain('v-else-if="!showDictation"')
    expect(prompt.indexOf('data-test-id="ai-prompt-dictation"')).toBeLessThan(
      prompt.indexOf('data-test-id="ai-prompt-send"')
    )
    expect(prompt).not.toContain('v-else-if="speechDictationAvailable"')
  })

  test('groups chronological activity once and collapses it when a run completes', async () => {
    const surface = await Bun.file('src/components/ai-elements/AiConversationSurface.vue').text()
    const activity = await Bun.file('src/components/ai-elements/AiActivityDisclosure.vue').text()
    const message = await Bun.file('src/components/ai-elements/AiMessage.vue').text()
    const timeline = await Bun.file('src/components/ai-elements/T3MessagesTimeline.tsx').text()
    const narrative = await Bun.file('src/components/ai-elements/T3NarrativeRow.tsx').text()
    const timelineLogic = await Bun.file(
      'src/components/ai-elements/t3-messages-timeline.logic.ts'
    ).text()
    const notices = await Bun.file('THIRD_PARTY_NOTICES.md').text()
    const boardChat = await Bun.file(
      'src/components/agent-terminal/AgentConversationBoardSurface.vue'
    ).text()

    expect(boardChat).toContain('conversationMessages')
    expect(boardChat).not.toContain(' compact')
    expect(surface).not.toContain('v-if="compact"')
    const runs = await Bun.file('src/components/ai-elements/conversation-runs.ts').text()
    expect(surface).toContain('<AiActivityDisclosure')
    const firstDisclosure = surface.slice(
      surface.indexOf('<AiActivityDisclosure'),
      surface.indexOf('/>', surface.indexOf('<AiActivityDisclosure')) + 2
    )
    expect(firstDisclosure).toContain('v-if="!botTextMode"')
    expect(surface).toContain('<AiBotPresence')
    expect(surface).toContain('v-for="{ run, runIndex } in paintedRuns"')
    expect(surface).toContain('conversationRuns(messages, { active: busy.value })')
    expect(surface).toContain('conversationRunWindow(')
    expect(runs).toContain(
      'endedAt: run.prompt?.completedAt ?? latestMessageCreatedAt(run.messages)'
    )
    expect(surface).toContain(':ended-at="run.endedAt"')
    expect(activity).toContain("import T3MessagesTimeline from './T3MessagesTimeline'")
    expect(activity).toContain('createRoot(element)')
    expect(activity).toContain('createElement(T3MessagesTimeline')
    expect(activity).toContain('data-test-id="t3-messages-timeline-island"')
    expect(surface.indexOf('<AiActivityDisclosure')).toBeLessThan(
      surface.indexOf('v-for="message in run.visible"')
    )
    expect(timeline).toContain('data-t3-source-revision="5d7665396083d285132d67038813862a93337ca5"')
    expect(timeline).toContain('import { T3NarrativeRow as NarrativeRow }')
    expect(narrative).toContain('assistantMarkdownNodes')
    expect(narrative).toContain('useSmoothedText')
    expect(timeline).toContain('findNearestVerticalScroller')
    expect(timeline).toContain('data-test-id="ai-tool-group-toggle"')
    expect(timeline).toContain('data-test-id="ai-turn-duration"')
    expect(timelineLogic).toContain('MAX_VISIBLE_WORK_LOG_ENTRIES = 1')
    expect(timelineLogic).toContain("kind: 'work-toggle'")
    expect(timelineLogic).toContain("id: 'working-indicator-row'")
    expect(timelineLogic).toContain('computeStableT3MessagesTimelineRows')
    expect(notices).toContain('T3 Code')
    expect(notices).toContain('MIT License')
    expect(message).not.toContain('hideActivity = true')
    expect(message).not.toContain('<AiReasoning')
    expect(message).not.toContain('<AiToolCall')
    expect(message).not.toContain(':compact="compact"')
  })

  test('uses a dedicated compact texting presentation only for Bot chats', async () => {
    const sidebar = await Bun.file('src/components/agent-chat/AgentChatsPanel.vue').text()
    const surface = await Bun.file('src/components/ai-elements/AiConversationSurface.vue').text()
    const message = await Bun.file('src/components/ai-elements/AiMessage.vue').text()
    const markdown = await Bun.file('src/components/ai-elements/AiMarkdown.vue').text()
    const prompt = await Bun.file('src/components/ai-elements/AiPromptInput.vue').text()
    const styles = await Bun.file('src/app.css').text()

    expect(sidebar).toContain('() => configuringBot.value || Boolean(selectedWorkMapBot.value)')
    expect(sidebar).toContain("messageMode: botTextMode ? 'bot-text' : 'task'")
    expect(surface).toContain(':data-conversation-mode="messageMode"')
    expect(surface).toContain(':message-mode="messageMode"')
    expect(surface).toContain(':compact="botTextMode"')
    expect(prompt).toContain("compactConversation ? 'pointer-events-none absolute inset-x-1")
    expect(surface).toContain('v-if="chapterRailReady && !botTextMode"')
    expect(surface).toContain('v-if="!botTextMode"')
    expect(surface).toContain('<AiBotPresence')
    expect(surface).toContain('v-if="latestTurnChanges && !botTextMode"')
    expect(surface).toContain('const BOT_TIME_SEPARATOR_MS = 30 * 60 * 1_000')
    expect(surface).toContain('data-test-id="ai-message-time-separator"')
    expect(surface).toContain(':datetime="run.startedAt"')
    expect(surface).toContain('class="py-2 text-center')
    expect(message).toContain("messageMode === 'bot-text'")
    expect(styles).toContain('--color-agent-bot-user-bubble: #3b3b40')
    expect(styles).toContain('--color-agent-bot-user-bubble: #050505')
    expect(message).toContain('bg-agent-bot-user-bubble px-3.5 py-2 text-white')
    expect(message).toContain('bg-agent-user-bubble px-3.5 py-2.5 text-agent-ink')
    expect(message).toContain('v-if="messageTime && !botTextMode"')
    expect(message).toContain('v-if="botTextMode" v-model:open="reactionMenuOpen"')
    expect(message).toContain('v-if="botTextMode && reaction"')
    expect(message).toContain('class="-mt-2.5 flex min-h-5 items-center"')
    expect(message).toContain("message.role === 'user' ? 'justify-end px-3' : 'justify-start px-3'")
    expect(message).toContain("? 'pointer-events-none absolute top-1/2 right-full")
    expect(message).toContain(": 'pointer-events-none absolute top-1/2 left-full")
    expect(message).toContain(":variant=\"botTextMode ? 'bot-text' : 'answer'\"")
    expect(markdown).toContain('class="assistant-text-bubble"')
    expect(markdown).toContain('block.nodes.flatMap((node, nodeIndex) =>')
    expect(markdown).toContain("node.type === 'thematicBreak'")
    expect(markdown).toContain("variant?: 'activity' | 'answer' | 'bot-text'")
    expect(prompt).toContain('data-test-id="ai-prompt-attach"')
    expect(prompt).toContain('data-test-id="ai-prompt-dictation"')
    expect(prompt).toContain('data-test-id="ai-prompt-send"')
    expect(prompt).toContain('v-if="showDictation && (!compactConversation || !showSend)"')
    expect(prompt).toContain('() => dictating.value || hasDraft.value || hasAnnotations.value')
  })

  test('opens changed files before the selected file diff in the T3 workspace', async () => {
    const pill = await Bun.file('src/components/ai-elements/AiTurnChanges.vue').text()
    const workspace = await Bun.file('src/components/ai-elements/T3RightPanelWorkspace.tsx').text()
    const diffSurface = await Bun.file('src/components/ai-elements/T3DiffSurface.tsx').text()
    const resize = await Bun.file('src/components/ai-elements/t3-right-panel-resize.ts').text()
    const diffReview = await Bun.file(
      'src/components/ai-elements/useConversationDiffReview.ts'
    ).text()
    const bridge = await Bun.file('src/components/ai-elements/AiRightPanelWorkspace.vue').text()
    const sidebar = await Bun.file('src/components/agent-chat/AgentChatsPanel.vue').text()
    const styles = await Bun.file('src/app.css').text()
    const notices = await Bun.file('THIRD_PARTY_NOTICES.md').text()

    expect(pill).toContain("emit('open-file', path)")
    expect(pill).toContain('Show files changed in latest turn')
    expect(pill).toContain('data-test-id="turn-changed-files"')
    expect(pill).toContain(':data-changed-file="file.path"')
    expect(pill).toContain('bottom-[calc(100%+8px)]')
    expect(pill).toContain('rounded-[10px] border border-border/70')
    expect(pill).not.toContain('whitespace-nowrap rounded-full')
    expect(pill).not.toContain('ai-turn-changes-details')
    expect(workspace).toContain(
      'data-t3-source-revision="e67074f80933a27bd3cdc4e24f486358407690fb"'
    )
    expect(workspace).toContain('data-test-id="t3-right-panel"')
    expect(workspace).toContain('role="separator"')
    expect(workspace).toContain('<T3DiffSurface')
    expect(resize).toContain('target.setPointerCapture(event.pointerId)')
    expect(resize).toContain('resizeHandlers: {')
    expect(resize).toContain('onLostPointerCapture: cancelResize')
    expect(resize).toContain('onPointerMove: moveResize')
    expect(resize).toContain('onPointerUp: endResize')
    expect(resize).not.toContain("window.addEventListener('pointermove'")
    expect(resize).toContain('lockHorizontalResizeCursor()')
    expect(workspace).toContain("resizing ? 'transition-none'")
    expect(workspace).toContain('aria-label="Resize right workspace"')
    expect(workspace).toContain("backgroundColor: 'rgb(0 0 0 / 0.005)'")
    expect(workspace).toContain("cursor: 'col-resize'")
    expect(diffSurface).toContain('data-diff-file={props.file.path}')
    expect(diffSurface).toContain('data-test-id="t3-diff-comment-editor"')
    expect(workspace).toContain("kind: 'browser'")
    expect(workspace).toContain("kind: 'terminal'")
    expect(workspace).toContain("kind: 'files'")
    expect(diffSurface).toContain('const displayedFiles = selectedFile ? [selectedFile] : files')
    expect(workspace).not.toContain("label: 'Agents'")
    expect(bridge).toContain('createElement(T3RightPanelWorkspace')
    expect(bridge).toContain('<Teleport to="body">')
    expect(styles).toContain('html[data-horizontal-resizing] *')
    expect(styles).toContain('cursor: col-resize !important')
    expect(diffReview).toContain('open-pencil:t3-right-panel-state-v1')
    expect(sidebar).not.toContain('data-test-id="agent-selected-diff"')
    expect(sidebar).not.toContain('function openLatestTurnDiff()')
    expect(sidebar).toContain('@open-diff="openTurnDiff"')
    expect(notices).toContain('RightPanelResizeHandle')
    expect(notices).toContain('e67074f80933a27bd3cdc4e24f486358407690fb')
  })

  test('keeps the Chats sidebar to one list or one conversation at a time', async () => {
    const [sidebarShell, workMapSurface] = await Promise.all([
      Bun.file('src/components/agent-chat/AgentChatsPanel.vue').text(),
      Bun.file('src/components/agent-chat/AgentWorkMapSurface.vue').text()
    ])
    const sidebarChat = `${sidebarShell}\n${workMapSurface}`

    expect(sidebarChat).toContain('const view = agentChatsPanelView')
    expect(sidebarChat).toContain('v-show="view === \'list\'"')
    expect(sidebarChat).toContain('v-show="view === \'conversation\'"')
    expect(sidebarChat).toContain('data-test-id="agent-thread-back"')
    expect(sidebarChat).toContain('data-test-id="agent-selected-new"')
    expect(sidebarChat).toContain('AgentThreadStatusIndicator')
    expect(sidebarChat).not.toContain('function stateTone')
    expect(sidebarChat).not.toContain('function showStateDot')
    expect(sidebarChat).not.toContain('v-for="thread in entry.threads.items"')
    expect(sidebarChat).not.toContain('DISPATCHERS')
    expect(sidebarChat).not.toContain('TASK HISTORY')
    expect(sidebarChat).not.toContain('agent-pool-summary')
    expect(sidebarChat).not.toContain('{{ thread.routingKey }}')
    expect(sidebarChat).not.toContain('agent-conversation-state')
    expect(sidebarChat).not.toContain('function headerStatus')
    expect(sidebarChat).not.toContain('panelTitle(selectedThread)')
    expect(sidebarChat).not.toContain(
      ':empty-description="threadLiveWorkingLabel(selectedThread, now.getTime())"'
    )
    expect(sidebarChat).not.toContain("kind === 'dispatcher'")
    expect(sidebarChat).toContain('agentConversationDisplayTitle(selectedThread)')

    const boardChat = await Bun.file(
      'src/components/agent-terminal/AgentConversationBoardSurface.vue'
    ).text()
    expect(boardChat).toContain('data-test-id="agent-conversation-working"')
    expect(boardChat).toContain('icon-lucide-loader-circle')
    expect(boardChat).not.toContain('agent-conversation-status-dot')
    expect(boardChat).not.toContain('agent-conversation-status-label')
    expect(boardChat).not.toContain(':empty-description="workingLabel || thread?.recentUpdate"')
    expect(boardChat).not.toContain('backdrop-blur-xl')
    expect(boardChat).not.toContain("kind === 'dispatcher'")

    const overlays = await Bun.file(
      'src/components/agent-terminal/AgentTerminalOverlays.vue'
    ).text()
    expect(overlays).not.toContain('AgentRoutingConnections')
    expect(overlays).not.toContain('createAgentTerminalDocument')
    expect(overlays).not.toContain('createAgentConversationBoardObject')
    expect(overlays).not.toContain('pendingConversationIds')
    expect(overlays).not.toContain('observeConversationInventory')
    expect(overlays).not.toContain('createDispatcherObject')
  })

  test('lets a click in the Board composer reach the input and enter the chat', async () => {
    const overlays = await Bun.file('src/components/canvas/CodeObjectOverlays.vue').text()
    const conversation = await Bun.file('src/components/ai-elements/AiConversation.vue').text()
    const prompt = await Bun.file('src/components/ai-elements/AiPromptInput.vue').text()
    const styles = await Bun.file('src/app.css').text()
    const boardChat = await Bun.file(
      'src/components/agent-terminal/AgentConversationBoardSurface.vue'
    ).text()

    expect(overlays).toContain('agentDocumentFor(frame)')
    expect(overlays).toContain('liveIframeHostStyle(style)')
    expect(overlays).toContain('isSmylrProductionFrame(frame) ||')
    expect(overlays).toContain('isSmylrComponentCodeObject(frame) ||')
    expect(overlays).not.toContain("contentVisibility: 'auto'")
    expect(overlays).toContain('@pointerdown.stop="beginSurfacePointerInteraction(frame, $event)"')
    expect(overlays).toContain('@pointerup.stop.prevent="endShapeMove"')
    expect(overlays).toContain("mode === 'interact' && frame && !agentDocumentFor(frame)")
    expect(conversation).toContain('tabindex="-1"')
    expect(conversation).not.toContain('tabindex="0"')
    expect(conversation).toContain('useStickToBottom')
    expect(boardChat).toContain('shouldRouteKeyToAgentComposer')
    expect(boardChat).toContain("surface.value?.querySelector('textarea')?.focus")
    expect(boardChat).toContain('composer.focus({ preventScroll: true })')
    expect(prompt).toContain('focusComposer')
    expect(prompt).toContain('select-text')
    expect(prompt).toContain('} = defineProps<')
    expect(prompt).not.toContain('useTextareaAutosize')
    expect(prompt).not.toContain('} = props')
    expect(boardChat).toContain('select-text')
    expect(boardChat).toContain('{ capture: true }')
    expect(styles).toContain('user-select: text')
    expect(styles).toContain('-webkit-user-select: text')
  })

  test('does not remount or snap the transcript on each working update', async () => {
    const conversation = await Bun.file('src/components/ai-elements/AiConversation.vue').text()
    const surface = await Bun.file('src/components/ai-elements/AiConversationSurface.vue').text()
    const annotations = await Bun.file(
      'src/components/ai-elements/AiConversationAnnotations.vue'
    ).text()
    const activity = await Bun.file('src/components/ai-elements/AiActivityDisclosure.vue').text()
    const modelSelect = await Bun.file(
      'src/components/ai-elements/AiModelAndEffortSelect.vue'
    ).text()
    const promptInput = await Bun.file('src/components/ai-elements/AiPromptInput.vue').text()
    const sidebarChat = await Bun.file('src/components/agent-chat/AgentChatsPanel.vue').text()
    const panelHistory = await Bun.file('src/app/agent-chat/panel-history-lifecycle.ts').text()
    const boardChat = await Bun.file(
      'src/components/agent-terminal/AgentConversationBoardSurface.vue'
    ).text()

    expect(conversation).toContain('ref="scrollRef"')
    expect(conversation).toContain('ref="contentRef"')
    expect(conversation).toContain('useStickToBottom')
    expect(conversation).toContain("resize: 'instant'")
    expect(conversation).toContain('defineExpose({ scrollToLatest })')
    expect(surface).toContain("scrollTranscriptToLatest('smooth')")
    expect(surface).not.toContain('viewport.scrollTop = viewport.scrollHeight')
    expect(conversation).not.toContain('pinToBottomIfLocked')
    expect(conversation).not.toContain('bindContentRef')
    expect(conversation).not.toContain('onUpdated')
    expect(surface).toContain('<AiConversationAnnotations')
    expect(annotations).toContain('function hasAnnotationLayout')
    expect(annotations).toContain('if (hasAnnotationLayout()) refreshAnnotationGeometry()')
    expect(annotations).toContain('if (!hasAnnotationLayout()) return')
    expect(activity).not.toContain('<Transition')
    expect(surface).toContain('conversationWindowFollowsLatest')
    const markdown = await Bun.file('src/components/ai-elements/AiMarkdown.vue').text()
    expect(markdown).toContain('useStreamedText')
    expect(surface).toContain('nextConversationRunHeight')
    expect(surface).toContain('allowShrink: !(busy.value && latest?.id === runId)')
    const toolGroup = await Bun.file('src/components/ai-elements/AiToolGroup.vue').text()
    expect(toolGroup).toContain(':css="!busy"')
    expect(toolGroup).not.toContain('if (shouldOpen) expanded.value = true')
    expect(activity).not.toContain('if (value) expanded.value = true')
    expect(toolGroup).not.toContain('appear')
    expect(sidebarChat).not.toContain('threadLiveWorkingLabel(selectedThread, now.getTime())')
    expect(boardChat).toContain("workingLabel: thread?.recentUpdate || ''")
    expect(boardChat).not.toContain('workingLabel: workingLabel')
    expect(sidebarChat).toContain('agentChatsPanelSelectedId')
    expect(sidebarChat).toContain('agentChatsPanelView')
    expect(panelHistory).toContain("agentChatsPanelView.value === 'conversation'")
    expect(sidebarChat).toContain("const conversationSurfaceKey = ref('conversation')")
    expect(sidebarChat).toContain('conversationSurfaceKey.value = thread.id')
    expect(sidebarChat).toContain('input?.focus({ preventScroll: true })')
    expect(sidebarChat).toContain('overflow-clip')
    expect(surface).toContain('overflow-clip')
    expect(conversation).toContain('overflow-clip')
    expect(modelSelect).toContain('@close-auto-focus.prevent')
    expect(promptInput).toContain('@close-auto-focus.prevent')
  })

  test('matches the thread-history scrollbar on the conversation transcript', async () => {
    const conversation = await Bun.file('src/components/ai-elements/AiConversation.vue').text()
    const historyScrollbar = await Bun.file('src/components/ui/AppScrollAreaScrollbar.vue').text()
    const styles = await Bun.file('src/app.css').text()
    const sidebarChat = await Bun.file('src/components/agent-chat/AgentWorkMapSurface.vue').text()

    expect(sidebarChat).toContain('<AppScrollAreaScrollbar />')
    expect(historyScrollbar).toContain('w-1.5')
    expect(historyScrollbar).toContain('p-px')
    expect(historyScrollbar).toContain('rounded-full bg-muted/30')
    expect(conversation).toContain('scrollbar-panel')
    expect(conversation).toContain('overflow-y-auto')
    expect(styles).toContain('@utility scrollbar-panel')
    expect(styles).toContain('var(--color-muted) 30%')
    expect(styles).toContain('width: 6px')
    expect(styles).toContain('border-radius: 9999px')
  })
})
