create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create table public.openpencil_workspaces (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'OpenPencil Workspace',
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.openpencil_workspace_members (
  workspace_id uuid not null references public.openpencil_workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner', 'editor')),
  created_at timestamptz not null default now(),
  primary key (workspace_id, user_id)
);

create table public.openpencil_documents (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.openpencil_workspaces(id) on delete cascade,
  slug text not null,
  name text not null,
  room_id text not null unique,
  snapshot_base64 text,
  snapshot_sequence bigint not null default 0,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint openpencil_documents_workspace_slug_key unique (workspace_id, slug),
  constraint openpencil_documents_slug_format
    check (slug ~ '^[a-z0-9][a-z0-9-]{0,62}$'),
  constraint openpencil_documents_snapshot_size
    check (snapshot_base64 is null or octet_length(snapshot_base64) <= 33554432)
);

create table public.openpencil_document_updates (
  sequence bigint generated by default as identity primary key,
  document_id uuid not null references public.openpencil_documents(id) on delete cascade,
  workspace_id uuid not null references public.openpencil_workspaces(id) on delete cascade,
  client_update_id uuid not null,
  update_base64 text not null,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  constraint openpencil_document_updates_document_client_key
    unique (document_id, client_update_id),
  constraint openpencil_document_updates_payload_size
    check (octet_length(update_base64) between 1 and 33554432)
);

create table public.openpencil_workspace_invites (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.openpencil_workspaces(id) on delete cascade,
  token_hash bytea not null unique,
  created_by uuid not null references auth.users(id),
  expires_at timestamptz not null,
  accepted_by uuid references auth.users(id),
  accepted_at timestamptz,
  created_at timestamptz not null default now()
);

create index openpencil_workspace_members_user_idx
  on public.openpencil_workspace_members (user_id, workspace_id);
create index openpencil_documents_workspace_idx
  on public.openpencil_documents (workspace_id);
create index openpencil_document_updates_document_sequence_idx
  on public.openpencil_document_updates (document_id, sequence);
create index openpencil_workspace_invites_workspace_idx
  on public.openpencil_workspace_invites (workspace_id, expires_at);

alter table public.openpencil_workspaces enable row level security;
alter table public.openpencil_workspace_members enable row level security;
alter table public.openpencil_documents enable row level security;
alter table public.openpencil_document_updates enable row level security;
alter table public.openpencil_workspace_invites enable row level security;

create or replace function public.is_openpencil_workspace_member(p_workspace_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.openpencil_workspace_members member
    where member.workspace_id = p_workspace_id
      and member.user_id = (select auth.uid())
  );
$$;

create policy openpencil_workspaces_member_select
  on public.openpencil_workspaces
  for select
  to authenticated
  using (public.is_openpencil_workspace_member(id));

create policy openpencil_workspace_members_member_select
  on public.openpencil_workspace_members
  for select
  to authenticated
  using (public.is_openpencil_workspace_member(workspace_id));

create policy openpencil_documents_member_select
  on public.openpencil_documents
  for select
  to authenticated
  using (public.is_openpencil_workspace_member(workspace_id));

create policy openpencil_document_updates_member_select
  on public.openpencil_document_updates
  for select
  to authenticated
  using (public.is_openpencil_workspace_member(workspace_id));

create policy openpencil_document_updates_member_insert
  on public.openpencil_document_updates
  for insert
  to authenticated
  with check (
    created_by = (select auth.uid())
    and public.is_openpencil_workspace_member(workspace_id)
    and exists (
      select 1
      from public.openpencil_documents document
      where document.id = document_id
        and document.workspace_id = workspace_id
    )
  );

create or replace function public.scope_openpencil_document_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  resolved_workspace_id uuid;
begin
  if (select auth.uid()) is null then
    raise exception 'OpenPencil update requires authentication'
      using errcode = '42501';
  end if;

  select document.workspace_id
  into resolved_workspace_id
  from public.openpencil_documents document
  where document.id = new.document_id;

  if resolved_workspace_id is null
    or not public.is_openpencil_workspace_member(resolved_workspace_id)
  then
    raise exception 'OpenPencil document is outside the current workspace'
      using errcode = '42501';
  end if;

  new.workspace_id := resolved_workspace_id;
  new.created_by := (select auth.uid());
  return new;
end;
$$;

create trigger scope_openpencil_document_update
before insert on public.openpencil_document_updates
for each row execute function public.scope_openpencil_document_update();

create or replace function public.openpencil_accept_invite(p_token text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  resolved_workspace_id uuid;
  resolved_invite_id uuid;
begin
  if current_user_id is null then
    raise exception 'Sign in before accepting an OpenPencil invite'
      using errcode = '42501';
  end if;

  if p_token is null or length(p_token) <> 64 or p_token !~ '^[0-9a-f]+$' then
    raise exception 'Invalid OpenPencil invite'
      using errcode = '22023';
  end if;

  select invite.id, invite.workspace_id
  into resolved_invite_id, resolved_workspace_id
  from public.openpencil_workspace_invites invite
  where invite.token_hash = extensions.digest(p_token, 'sha256')
    and invite.accepted_at is null
    and invite.expires_at > now()
  for update;

  if resolved_invite_id is null then
    raise exception 'OpenPencil invite is invalid or expired'
      using errcode = '22023';
  end if;

  insert into public.openpencil_workspace_members (workspace_id, user_id, role)
  values (resolved_workspace_id, current_user_id, 'editor')
  on conflict (workspace_id, user_id) do nothing;

  update public.openpencil_workspace_invites
  set accepted_by = current_user_id,
      accepted_at = now()
  where id = resolved_invite_id;

  return resolved_workspace_id;
end;
$$;

create or replace function public.openpencil_bootstrap_workspace(p_workspace_id uuid default null)
returns table (
  workspace_id uuid,
  document_id uuid,
  room_id text,
  workspace_name text,
  document_name text,
  member_role text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  resolved_workspace_id uuid;
  resolved_document_id uuid;
begin
  if current_user_id is null then
    raise exception 'OpenPencil workspace requires authentication'
      using errcode = '42501';
  end if;

  if p_workspace_id is not null and exists (
    select 1
    from public.openpencil_workspace_members member
    where member.workspace_id = p_workspace_id
      and member.user_id = current_user_id
  ) then
    resolved_workspace_id := p_workspace_id;
  else
    select member.workspace_id
    into resolved_workspace_id
    from public.openpencil_workspace_members member
    where member.user_id = current_user_id
    order by member.created_at, member.workspace_id
    limit 1;
  end if;

  if resolved_workspace_id is null then
    insert into public.openpencil_workspaces (name, created_by)
    values ('OpenPencil Workspace', current_user_id)
    returning id into resolved_workspace_id;

    insert into public.openpencil_workspace_members (workspace_id, user_id, role)
    values (resolved_workspace_id, current_user_id, 'owner');
  end if;

  select document.id
  into resolved_document_id
  from public.openpencil_documents document
  where document.workspace_id = resolved_workspace_id
    and document.slug = 'production-canvas';

  if resolved_document_id is null then
    resolved_document_id := gen_random_uuid();
    insert into public.openpencil_documents (
      id,
      workspace_id,
      slug,
      name,
      room_id,
      created_by
    ) values (
      resolved_document_id,
      resolved_workspace_id,
      'production-canvas',
      'OpenPencil Production Canvas',
      'op-' || replace(resolved_document_id::text, '-', ''),
      current_user_id
    );
  end if;

  return query
  select
    workspace.id,
    document.id,
    document.room_id,
    workspace.name,
    document.name,
    member.role
  from public.openpencil_workspaces workspace
  join public.openpencil_workspace_members member
    on member.workspace_id = workspace.id
   and member.user_id = current_user_id
  join public.openpencil_documents document
    on document.id = resolved_document_id
  where workspace.id = resolved_workspace_id;
end;
$$;

create or replace function public.openpencil_create_invite(p_workspace_id uuid)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  invite_token text;
begin
  if current_user_id is null then
    raise exception 'OpenPencil invite requires authentication'
      using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.openpencil_workspace_members member
    where member.workspace_id = p_workspace_id
      and member.user_id = current_user_id
      and member.role = 'owner'
  ) then
    raise exception 'Only the workspace owner can create an invite'
      using errcode = '42501';
  end if;

  invite_token := encode(extensions.gen_random_bytes(32), 'hex');
  insert into public.openpencil_workspace_invites (
    workspace_id,
    token_hash,
    created_by,
    expires_at
  ) values (
    p_workspace_id,
    extensions.digest(invite_token, 'sha256'),
    current_user_id,
    now() + interval '7 days'
  );

  return invite_token;
end;
$$;

create or replace function public.openpencil_checkpoint_document(
  p_document_id uuid,
  p_snapshot_base64 text,
  p_covers_sequence bigint
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  resolved_workspace_id uuid;
  maximum_sequence bigint;
  current_snapshot_sequence bigint;
begin
  select document.workspace_id, document.snapshot_sequence
  into resolved_workspace_id, current_snapshot_sequence
  from public.openpencil_documents document
  where document.id = p_document_id
  for update;

  if resolved_workspace_id is null
    or not public.is_openpencil_workspace_member(resolved_workspace_id)
  then
    raise exception 'OpenPencil document is outside the current workspace'
      using errcode = '42501';
  end if;

  if p_snapshot_base64 is null
    or octet_length(p_snapshot_base64) = 0
    or octet_length(p_snapshot_base64) > 33554432
  then
    raise exception 'Invalid OpenPencil checkpoint payload'
      using errcode = '22023';
  end if;

  select coalesce(max(document_update.sequence), current_snapshot_sequence)
  into maximum_sequence
  from public.openpencil_document_updates document_update
  where document_update.document_id = p_document_id;

  if p_covers_sequence > maximum_sequence then
    raise exception 'Checkpoint sequence exceeds the durable update log'
      using errcode = '22023';
  end if;

  if p_covers_sequence <= current_snapshot_sequence then
    return false;
  end if;

  update public.openpencil_documents
  set snapshot_base64 = p_snapshot_base64,
      snapshot_sequence = p_covers_sequence,
      updated_at = now()
  where id = p_document_id;

  delete from public.openpencil_document_updates
  where document_id = p_document_id
    and sequence <= p_covers_sequence;

  return true;
end;
$$;

revoke all on table public.openpencil_workspaces from anon, authenticated;
revoke all on table public.openpencil_workspace_members from anon, authenticated;
revoke all on table public.openpencil_documents from anon, authenticated;
revoke all on table public.openpencil_document_updates from anon, authenticated;
revoke all on table public.openpencil_workspace_invites from anon, authenticated;

grant select on table public.openpencil_workspaces to authenticated;
grant select on table public.openpencil_workspace_members to authenticated;
grant select on table public.openpencil_documents to authenticated;
grant select, insert on table public.openpencil_document_updates to authenticated;
grant usage, select on sequence public.openpencil_document_updates_sequence_seq to authenticated;

revoke all on function public.is_openpencil_workspace_member(uuid) from public;
grant execute on function public.is_openpencil_workspace_member(uuid) to authenticated;
revoke all on function public.openpencil_accept_invite(text) from public;
grant execute on function public.openpencil_accept_invite(text) to authenticated;
revoke all on function public.openpencil_bootstrap_workspace(uuid) from public;
grant execute on function public.openpencil_bootstrap_workspace(uuid) to authenticated;
revoke all on function public.openpencil_create_invite(uuid) from public;
grant execute on function public.openpencil_create_invite(uuid) to authenticated;
revoke all on function public.openpencil_checkpoint_document(uuid, text, bigint) from public;
grant execute on function public.openpencil_checkpoint_document(uuid, text, bigint) to authenticated;

do $$
begin
  alter publication supabase_realtime add table public.openpencil_document_updates;
exception
  when duplicate_object then null;
end;
$$;
